//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilSemProjekt.MVVM.LocationServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/MobileService.Model")]
    public partial class Location : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double LatitudeField;
        
        private string LocationDescriptionField;
        
        private int LocationIdField;
        
        private string LocationNameField;
        
        private double LongitudeField;
        
        private System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Picture> PicturesField;
        
        private System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Rating> RatingsField;
        
        private MobilSemProjekt.MVVM.LocationServiceReference.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationDescription {
            get {
                return this.LocationDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationDescriptionField, value) != true)) {
                    this.LocationDescriptionField = value;
                    this.RaisePropertyChanged("LocationDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Picture> Pictures {
            get {
                return this.PicturesField;
            }
            set {
                if ((object.ReferenceEquals(this.PicturesField, value) != true)) {
                    this.PicturesField = value;
                    this.RaisePropertyChanged("Pictures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Rating> Ratings {
            get {
                return this.RatingsField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingsField, value) != true)) {
                    this.RatingsField = value;
                    this.RaisePropertyChanged("Ratings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobilSemProjekt.MVVM.LocationServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/MobileService.Model")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string HashPasswordField;
        
        private string SaltField;
        
        private int UserIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashPassword {
            get {
                return this.HashPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HashPasswordField, value) != true)) {
                    this.HashPasswordField = value;
                    this.RaisePropertyChanged("HashPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((object.ReferenceEquals(this.SaltField, value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/MobileService.Model")]
    public partial class Picture : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private int PictureIdField;
        
        private string PictureNameField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PictureId {
            get {
                return this.PictureIdField;
            }
            set {
                if ((this.PictureIdField.Equals(value) != true)) {
                    this.PictureIdField = value;
                    this.RaisePropertyChanged("PictureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureName {
            get {
                return this.PictureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureNameField, value) != true)) {
                    this.PictureNameField = value;
                    this.RaisePropertyChanged("PictureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rating", Namespace="http://schemas.datacontract.org/2004/07/MobileService.Model")]
    public partial class Rating : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CommentField;
        
        private double RateField;
        
        private int RatingIdField;
        
        private MobilSemProjekt.MVVM.LocationServiceReference.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RatingId {
            get {
                return this.RatingIdField;
            }
            set {
                if ((this.RatingIdField.Equals(value) != true)) {
                    this.RatingIdField = value;
                    this.RaisePropertyChanged("RatingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobilSemProjekt.MVVM.LocationServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocationServiceReference.ILocationService")]
    public interface ILocationService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILocationService/GetLocationById", ReplyAction="http://tempuri.org/ILocationService/GetLocationByIdResponse")]
        System.IAsyncResult BeginGetLocationById(int locationId, System.AsyncCallback callback, object asyncState);
        
        MobilSemProjekt.MVVM.LocationServiceReference.Location EndGetLocationById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILocationService/CreateLocation", ReplyAction="http://tempuri.org/ILocationService/CreateLocationResponse")]
        System.IAsyncResult BeginCreateLocation(MobilSemProjekt.MVVM.LocationServiceReference.Location location, System.AsyncCallback callback, object asyncState);
        
        int EndCreateLocation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILocationService/GetLocationsByTagName", ReplyAction="http://tempuri.org/ILocationService/GetLocationsByTagNameResponse")]
        System.IAsyncResult BeginGetLocationsByTagName(string tagName, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> EndGetLocationsByTagName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILocationService/GetLocationByLocationName", ReplyAction="http://tempuri.org/ILocationService/GetLocationByLocationNameResponse")]
        System.IAsyncResult BeginGetLocationByLocationName(string locationName, System.AsyncCallback callback, object asyncState);
        
        MobilSemProjekt.MVVM.LocationServiceReference.Location EndGetLocationByLocationName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILocationService/GetAllLocations", ReplyAction="http://tempuri.org/ILocationService/GetAllLocationsResponse")]
        System.IAsyncResult BeginGetAllLocations(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> EndGetAllLocations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILocationService/TestMethod", ReplyAction="http://tempuri.org/ILocationService/TestMethodResponse")]
        System.IAsyncResult BeginTestMethod(System.AsyncCallback callback, object asyncState);
        
        string EndTestMethod(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationServiceChannel : MobilSemProjekt.MVVM.LocationServiceReference.ILocationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLocationByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLocationByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MobilSemProjekt.MVVM.LocationServiceReference.Location Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MobilSemProjekt.MVVM.LocationServiceReference.Location)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLocationsByTagNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLocationsByTagNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLocationByLocationNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLocationByLocationNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MobilSemProjekt.MVVM.LocationServiceReference.Location Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MobilSemProjekt.MVVM.LocationServiceReference.Location)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllLocationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllLocationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestMethodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestMethodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationServiceClient : System.ServiceModel.ClientBase<MobilSemProjekt.MVVM.LocationServiceReference.ILocationService>, MobilSemProjekt.MVVM.LocationServiceReference.ILocationService {
        
        private BeginOperationDelegate onBeginGetLocationByIdDelegate;
        
        private EndOperationDelegate onEndGetLocationByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetLocationByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateLocationDelegate;
        
        private EndOperationDelegate onEndCreateLocationDelegate;
        
        private System.Threading.SendOrPostCallback onCreateLocationCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLocationsByTagNameDelegate;
        
        private EndOperationDelegate onEndGetLocationsByTagNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetLocationsByTagNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLocationByLocationNameDelegate;
        
        private EndOperationDelegate onEndGetLocationByLocationNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetLocationByLocationNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllLocationsDelegate;
        
        private EndOperationDelegate onEndGetAllLocationsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllLocationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginTestMethodDelegate;
        
        private EndOperationDelegate onEndTestMethodDelegate;
        
        private System.Threading.SendOrPostCallback onTestMethodCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LocationServiceClient() : 
                base(LocationServiceClient.GetDefaultBinding(), LocationServiceClient.GetDefaultEndpointAddress()) {
        }
        
        public LocationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LocationServiceClient.GetBindingForEndpoint(endpointConfiguration), LocationServiceClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public LocationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LocationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public LocationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LocationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public LocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetLocationByIdCompletedEventArgs> GetLocationByIdCompleted;
        
        public event System.EventHandler<CreateLocationCompletedEventArgs> CreateLocationCompleted;
        
        public event System.EventHandler<GetLocationsByTagNameCompletedEventArgs> GetLocationsByTagNameCompleted;
        
        public event System.EventHandler<GetLocationByLocationNameCompletedEventArgs> GetLocationByLocationNameCompleted;
        
        public event System.EventHandler<GetAllLocationsCompletedEventArgs> GetAllLocationsCompleted;
        
        public event System.EventHandler<TestMethodCompletedEventArgs> TestMethodCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.BeginGetLocationById(int locationId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLocationById(locationId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobilSemProjekt.MVVM.LocationServiceReference.Location MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.EndGetLocationById(System.IAsyncResult result) {
            return base.Channel.EndGetLocationById(result);
        }
        
        private System.IAsyncResult OnBeginGetLocationById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int locationId = ((int)(inValues[0]));
            return ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).BeginGetLocationById(locationId, callback, asyncState);
        }
        
        private object[] OnEndGetLocationById(System.IAsyncResult result) {
            MobilSemProjekt.MVVM.LocationServiceReference.Location retVal = ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).EndGetLocationById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLocationByIdCompleted(object state) {
            if ((this.GetLocationByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLocationByIdCompleted(this, new GetLocationByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLocationByIdAsync(int locationId) {
            this.GetLocationByIdAsync(locationId, null);
        }
        
        public void GetLocationByIdAsync(int locationId, object userState) {
            if ((this.onBeginGetLocationByIdDelegate == null)) {
                this.onBeginGetLocationByIdDelegate = new BeginOperationDelegate(this.OnBeginGetLocationById);
            }
            if ((this.onEndGetLocationByIdDelegate == null)) {
                this.onEndGetLocationByIdDelegate = new EndOperationDelegate(this.OnEndGetLocationById);
            }
            if ((this.onGetLocationByIdCompletedDelegate == null)) {
                this.onGetLocationByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLocationByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetLocationByIdDelegate, new object[] {
                        locationId}, this.onEndGetLocationByIdDelegate, this.onGetLocationByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.BeginCreateLocation(MobilSemProjekt.MVVM.LocationServiceReference.Location location, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateLocation(location, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.EndCreateLocation(System.IAsyncResult result) {
            return base.Channel.EndCreateLocation(result);
        }
        
        private System.IAsyncResult OnBeginCreateLocation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MobilSemProjekt.MVVM.LocationServiceReference.Location location = ((MobilSemProjekt.MVVM.LocationServiceReference.Location)(inValues[0]));
            return ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).BeginCreateLocation(location, callback, asyncState);
        }
        
        private object[] OnEndCreateLocation(System.IAsyncResult result) {
            int retVal = ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).EndCreateLocation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateLocationCompleted(object state) {
            if ((this.CreateLocationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateLocationCompleted(this, new CreateLocationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateLocationAsync(MobilSemProjekt.MVVM.LocationServiceReference.Location location) {
            this.CreateLocationAsync(location, null);
        }
        
        public void CreateLocationAsync(MobilSemProjekt.MVVM.LocationServiceReference.Location location, object userState) {
            if ((this.onBeginCreateLocationDelegate == null)) {
                this.onBeginCreateLocationDelegate = new BeginOperationDelegate(this.OnBeginCreateLocation);
            }
            if ((this.onEndCreateLocationDelegate == null)) {
                this.onEndCreateLocationDelegate = new EndOperationDelegate(this.OnEndCreateLocation);
            }
            if ((this.onCreateLocationCompletedDelegate == null)) {
                this.onCreateLocationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateLocationCompleted);
            }
            base.InvokeAsync(this.onBeginCreateLocationDelegate, new object[] {
                        location}, this.onEndCreateLocationDelegate, this.onCreateLocationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.BeginGetLocationsByTagName(string tagName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLocationsByTagName(tagName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.EndGetLocationsByTagName(System.IAsyncResult result) {
            return base.Channel.EndGetLocationsByTagName(result);
        }
        
        private System.IAsyncResult OnBeginGetLocationsByTagName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string tagName = ((string)(inValues[0]));
            return ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).BeginGetLocationsByTagName(tagName, callback, asyncState);
        }
        
        private object[] OnEndGetLocationsByTagName(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> retVal = ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).EndGetLocationsByTagName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLocationsByTagNameCompleted(object state) {
            if ((this.GetLocationsByTagNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLocationsByTagNameCompleted(this, new GetLocationsByTagNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLocationsByTagNameAsync(string tagName) {
            this.GetLocationsByTagNameAsync(tagName, null);
        }
        
        public void GetLocationsByTagNameAsync(string tagName, object userState) {
            if ((this.onBeginGetLocationsByTagNameDelegate == null)) {
                this.onBeginGetLocationsByTagNameDelegate = new BeginOperationDelegate(this.OnBeginGetLocationsByTagName);
            }
            if ((this.onEndGetLocationsByTagNameDelegate == null)) {
                this.onEndGetLocationsByTagNameDelegate = new EndOperationDelegate(this.OnEndGetLocationsByTagName);
            }
            if ((this.onGetLocationsByTagNameCompletedDelegate == null)) {
                this.onGetLocationsByTagNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLocationsByTagNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetLocationsByTagNameDelegate, new object[] {
                        tagName}, this.onEndGetLocationsByTagNameDelegate, this.onGetLocationsByTagNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.BeginGetLocationByLocationName(string locationName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLocationByLocationName(locationName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MobilSemProjekt.MVVM.LocationServiceReference.Location MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.EndGetLocationByLocationName(System.IAsyncResult result) {
            return base.Channel.EndGetLocationByLocationName(result);
        }
        
        private System.IAsyncResult OnBeginGetLocationByLocationName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string locationName = ((string)(inValues[0]));
            return ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).BeginGetLocationByLocationName(locationName, callback, asyncState);
        }
        
        private object[] OnEndGetLocationByLocationName(System.IAsyncResult result) {
            MobilSemProjekt.MVVM.LocationServiceReference.Location retVal = ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).EndGetLocationByLocationName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLocationByLocationNameCompleted(object state) {
            if ((this.GetLocationByLocationNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLocationByLocationNameCompleted(this, new GetLocationByLocationNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLocationByLocationNameAsync(string locationName) {
            this.GetLocationByLocationNameAsync(locationName, null);
        }
        
        public void GetLocationByLocationNameAsync(string locationName, object userState) {
            if ((this.onBeginGetLocationByLocationNameDelegate == null)) {
                this.onBeginGetLocationByLocationNameDelegate = new BeginOperationDelegate(this.OnBeginGetLocationByLocationName);
            }
            if ((this.onEndGetLocationByLocationNameDelegate == null)) {
                this.onEndGetLocationByLocationNameDelegate = new EndOperationDelegate(this.OnEndGetLocationByLocationName);
            }
            if ((this.onGetLocationByLocationNameCompletedDelegate == null)) {
                this.onGetLocationByLocationNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLocationByLocationNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetLocationByLocationNameDelegate, new object[] {
                        locationName}, this.onEndGetLocationByLocationNameDelegate, this.onGetLocationByLocationNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.BeginGetAllLocations(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllLocations(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.EndGetAllLocations(System.IAsyncResult result) {
            return base.Channel.EndGetAllLocations(result);
        }
        
        private System.IAsyncResult OnBeginGetAllLocations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).BeginGetAllLocations(callback, asyncState);
        }
        
        private object[] OnEndGetAllLocations(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> retVal = ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).EndGetAllLocations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllLocationsCompleted(object state) {
            if ((this.GetAllLocationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllLocationsCompleted(this, new GetAllLocationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllLocationsAsync() {
            this.GetAllLocationsAsync(null);
        }
        
        public void GetAllLocationsAsync(object userState) {
            if ((this.onBeginGetAllLocationsDelegate == null)) {
                this.onBeginGetAllLocationsDelegate = new BeginOperationDelegate(this.OnBeginGetAllLocations);
            }
            if ((this.onEndGetAllLocationsDelegate == null)) {
                this.onEndGetAllLocationsDelegate = new EndOperationDelegate(this.OnEndGetAllLocations);
            }
            if ((this.onGetAllLocationsCompletedDelegate == null)) {
                this.onGetAllLocationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllLocationsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllLocationsDelegate, null, this.onEndGetAllLocationsDelegate, this.onGetAllLocationsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.BeginTestMethod(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTestMethod(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string MobilSemProjekt.MVVM.LocationServiceReference.ILocationService.EndTestMethod(System.IAsyncResult result) {
            return base.Channel.EndTestMethod(result);
        }
        
        private System.IAsyncResult OnBeginTestMethod(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).BeginTestMethod(callback, asyncState);
        }
        
        private object[] OnEndTestMethod(System.IAsyncResult result) {
            string retVal = ((MobilSemProjekt.MVVM.LocationServiceReference.ILocationService)(this)).EndTestMethod(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestMethodCompleted(object state) {
            if ((this.TestMethodCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestMethodCompleted(this, new TestMethodCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestMethodAsync() {
            this.TestMethodAsync(null);
        }
        
        public void TestMethodAsync(object userState) {
            if ((this.onBeginTestMethodDelegate == null)) {
                this.onBeginTestMethodDelegate = new BeginOperationDelegate(this.OnBeginTestMethod);
            }
            if ((this.onEndTestMethodDelegate == null)) {
                this.onEndTestMethodDelegate = new EndOperationDelegate(this.OnEndTestMethod);
            }
            if ((this.onTestMethodCompletedDelegate == null)) {
                this.onTestMethodCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestMethodCompleted);
            }
            base.InvokeAsync(this.onBeginTestMethodDelegate, null, this.onEndTestMethodDelegate, this.onTestMethodCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MobilSemProjekt.MVVM.LocationServiceReference.ILocationService CreateChannel() {
            return new LocationServiceClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILocationService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILocationService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/LocationService/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return LocationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILocationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return LocationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILocationService);
        }
        
        private class LocationServiceClientChannel : ChannelBase<MobilSemProjekt.MVVM.LocationServiceReference.ILocationService>, MobilSemProjekt.MVVM.LocationServiceReference.ILocationService {
            
            public LocationServiceClientChannel(System.ServiceModel.ClientBase<MobilSemProjekt.MVVM.LocationServiceReference.ILocationService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetLocationById(int locationId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = locationId;
                System.IAsyncResult _result = base.BeginInvoke("GetLocationById", _args, callback, asyncState);
                return _result;
            }
            
            public MobilSemProjekt.MVVM.LocationServiceReference.Location EndGetLocationById(System.IAsyncResult result) {
                object[] _args = new object[0];
                MobilSemProjekt.MVVM.LocationServiceReference.Location _result = ((MobilSemProjekt.MVVM.LocationServiceReference.Location)(base.EndInvoke("GetLocationById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateLocation(MobilSemProjekt.MVVM.LocationServiceReference.Location location, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = location;
                System.IAsyncResult _result = base.BeginInvoke("CreateLocation", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCreateLocation(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CreateLocation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLocationsByTagName(string tagName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = tagName;
                System.IAsyncResult _result = base.BeginInvoke("GetLocationsByTagName", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> EndGetLocationsByTagName(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> _result = ((System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location>)(base.EndInvoke("GetLocationsByTagName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLocationByLocationName(string locationName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = locationName;
                System.IAsyncResult _result = base.BeginInvoke("GetLocationByLocationName", _args, callback, asyncState);
                return _result;
            }
            
            public MobilSemProjekt.MVVM.LocationServiceReference.Location EndGetLocationByLocationName(System.IAsyncResult result) {
                object[] _args = new object[0];
                MobilSemProjekt.MVVM.LocationServiceReference.Location _result = ((MobilSemProjekt.MVVM.LocationServiceReference.Location)(base.EndInvoke("GetLocationByLocationName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllLocations(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllLocations", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> EndGetAllLocations(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location> _result = ((System.Collections.ObjectModel.ObservableCollection<MobilSemProjekt.MVVM.LocationServiceReference.Location>)(base.EndInvoke("GetAllLocations", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTestMethod(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("TestMethod", _args, callback, asyncState);
                return _result;
            }
            
            public string EndTestMethod(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("TestMethod", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ILocationService,
        }
    }
}
